apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blog-api
  name: blog-api
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-api
  strategy: {}
  template:
    metadata:
      labels:
        app: blog-api
    spec:
      containers:
        - image: naohirokurasawa/blog-api
          name: blog-api
          ports:
            - containerPort: 8080
          resources: {}