apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog-api
  name: blog-api
  namespace: blog
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: blog-api