// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Content struct {
	ID   string `json:"id"`
	Body string `json:"body"`
}

type NewArticle struct {
	Slug        string `json:"slug"`
	Title       string `json:"title"`
	Date        string `json:"date"`
	CoverImage  string `json:"coverImage"`
	Content     string `json:"content"`
	Description string `json:"description"`
}
